import = ["/Users/robenkleene/.config/alacritty/modifiers.toml", "/Users/robenkleene/.config/alacritty/robenkleene.toml"]

[env]
ALACRITTY = "1"
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[window]
dimensions = { columns = 80, lines = 48 }
# Fixes `M-n`
option_as_alt = "Both"
